name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Setup Firefox
        uses: browser-actions/setup-firefox@v1

      - name: Setup geckodriver
        uses: browser-actions/setup-geckodriver@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install docs-gen
        run: cargo install --path .

      - name: Init
        run: docs-gen init docs-src

      - name: Run check
        run: docs-gen check docs-src

      - name: Run tests
        run: |
          cargo test --release
          cargo test --release --test e2e -- --ignored --test-threads=1
